[phases.build]
# Явно говорим зайти в папку и запустить сборку Rust
cmds = ["cd roomer_backend && cargo build --release"]

[start]
# Явно говорим, откуда запускать готовый бинарник
cmd = "./roomer_backend/target/release/roomer_backend"
